ci:
  config:
    schema_version: 1
    trunk_branch: main
    triggers:
      - src/**
    cli_version: v0.7.0-rc.0
    tag_prefix: rel-
    state_token: ${{ secrets.CASCADE_STATE_TOKEN }}
    manifest_file: .github/manifest.yaml
    manifest_key: ci
    builds:
      - name: lib
        workflow: .github/workflows/build-lib.yaml
        triggers: []
    changelog:
      contributors: true
  state:
    prerelease:
      sha: bf175035eec29f1b5a2d9ce0b5d7a679a1f28bf1
      version: rel-0.1.0-rc.0
      committed_at: "2026-07-01T07:57:55Z"
      committed_by: joshua-temple
