ci:
  config:
    schema_version: 1
    trunk_branch: main
    triggers:
      - src/**
    cli_version: v0.5.1
    tag_prefix: rel-
    state_token: ${{ secrets.CASCADE_STATE_TOKEN }}
    manifest_file: .github/manifest.yaml
    manifest_key: ci
    builds:
      - name: lib
        workflow: .github/workflows/build-lib.yaml
        triggers: []
    changelog:
      contributors: true
  state:
    prerelease:
      sha: be0bb08af94b5a9da7f314576f4a4daf8e7d85d8
      version: rel-0.1.0-rc.0
      committed_at: "2026-06-26T22:45:23Z"
      committed_by: joshua-temple
